/** Libellés d'affichage des clés d'infobox (clé technique → libellé FR). */
const INFOBOX_LABELS: Record<string, string> = {
  constructeur: "Constructeur",
  role: "Rôle",
  armees: "Armées",
  armee: "Armée",
  miseEnService: "Mise en service",
  statut: "Statut",
  equipage: "Équipage",
  motorisation: "Motorisation",
  vitesseMax: "Vitesse max",
  plafond: "Plafond",
  rayonDAction: "Rayon d'action",
  armementPrincipal: "Armement principal",
  capaciteEmport: "Capacité d'emport",
  type: "Type",
  classe: "Classe",
  portDAttache: "Port d'attache",
  deplacement: "Déplacement",
  longueur: "Longueur",
  aeronefsEmbarques: "Aéronefs embarqués",
  nomComplet: "Nom complet",
  code: "Code",
  localisation: "Localisation",
  unitesStationnees: "Unités stationnées",
  appareilsPresents: "Appareils présents",
  effectifs: "Effectifs",
  rattachement: "Rattachement",
  flottilles: "Flottilles",
  appellation: "Appellation",
  subordination: "Subordination",
  garnison: "Garnison",
  base: "Base",
  ban: "BAN",
  appareils: "Appareils",
  missions: "Missions",
  insigne: "Insigne",
  devise: "Devise",
  traditions: "Traditions",
  guidage: "Guidage",
  portee: "Portée",
  porteurs: "Porteurs",
  masse: "Masse",
  vitesse: "Vitesse",
  tutelle: "Tutelle",
  etatMajor: "État-major",
  creation: "Création",
  categorie: "Catégorie",
  codeOtan: "Code OTAN",
  echelon: "Échelon",
  dimensions: "Dimensions",
};

export function infoboxLabel(key: string): string {
  return INFOBOX_LABELS[key] ?? key.charAt(0).toUpperCase() + key.slice(1);
}
